language: cpp

os:
  - linux
  - osx

env:
  - variant=test_debug
  - variant=test_release
  - variant=test_barebones

compiler:
  - gcc
  - clang

# container-based builds
sudo: false
cache:
  directories:
    - $HOME/.ccache

# sources  list: https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json,
# packages list: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
addons:
  apt:
    sources:
    - boost-latest
    packages:
    - libboost1.55-all-dev
    - python2.7-dev

install:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then sudo brew install boost boost-build python27-dev; fi
  - 'echo "using gcc : : ccache g++ ;" > ~/user-config.jam'
  - 'echo "using clang : : ccache clang++ ;" >> ~/user-config.jam'
  - 'echo "using python : 2.7 ;" >> ~/user-config.jam'
  - ccache -V && ccache --show-stats && ccache --zero-stats
  - which $CXX
  - ls -la `which $CXX`

script:
  - cd test
  - bjam -j 3 variant=$variant warnings=off -l900 $CC
  - cd ../examples
  - bjam -j 3 variant=$variant warnings=off $CC
  - cd ../bindings/python
  - bjam -j 3 variant=$variant warnings=off $CC stage_module
  - LD_LIBRARY_PATH=. python test.py
  - ccache --show-stats
